### ISSUE TITLE
Certain strings cause exceptions

### ISSUE THREAD

**Issue by kamronbatman** [eddyystop/joi-errors-for-forms#5]
I attempted to validate a URI with the value 'https://|' and I received an exception.

Additionally, but not as important, this library forces violation the following ESLint rule: https://eslint.org/docs/rules/no-template-curly-in-string

**Comment by eddyystop** [comment]
Was the exception thrown by Joi? Else, what line in the repo threw?

**Comment by kamronbatman** [comment]
I think I found out what the problem was.  I did not include 'string.uri' type.  The error was not very clear though.
